(() => {
  const fps = 30, duration = 140, maxFrame = duration * fps - 1;
  const cue = [
    [0,12,"Delegation should be deliberate. Mars Cost Router guides explicit model, effort, and context choices, calls for bounded child tasks, and keeps final verification with the root."],
    [12,27,"Mars Cost Router is an independent, unofficial delegation policy for Codex. Mars names the project; Terra and Sol name the requested model lanes. The focus is transparent requested settings and root-owned verification."],
    [27,43,"Economy requests Terra with low reasoning for bounded inspection. Balanced requests Terra with medium reasoning for focused implementation and review. Premium requests Sol with high reasoning for security, uncertainty, and difficult debugging."],
    [43,58,"Installation takes two public marketplace commands, followed by a new Codex session. Remote installation succeeded on Codex CLI 0.144.5, and hosted CI passes on Windows and Linux with Python 3.10 and 3.13."],
    [58,78,"The installed package is instruction-only and fully inspectable: one skill, one versioned policy, and plugin metadata. It guides the root to request explicit child settings and a bounded self-contained message; the root owns scope, integration, and final verification."],
    [78,94,"Each lane template calls for a generic privacy-safe task label, explicit model and effort, and fork turns set to none. The root selects bounded context, while requested route intent stays visible for review."],
    [94,110,"Across three precommitted pairs of four fixed read-only tasks, the selective Terra and Sol policy and the all-Sol high baseline each passed twelve of twelve deterministic checks, with zero observed automatic retries and reroutes."],
    [110,126,"Child-token totals were nearly flat: 356,116 versus 356,494, a recorded difference of minus 0.11 percent. Using the dated Standard API listed rates, the published comparison indexes Terra at 50 and Sol at 100 across the recorded categories."],
    [126,133,"Transparent provenance keeps the fixed-series record and dated rate comparison separate. See Evidence for scope and methodology."],
    [133,140,"Choose the lane. Bound the task. Verify at the root. Requested settings stay explicit and reviewable."]
  ];
  const chapters = ['POLICY','IDENTITY','LANES','INSTALL','ARCHITECTURE','ROUTE INTENT','EVIDENCE','RECORDED','METHOD','OUTRO'];
  const q = new URLSearchParams(location.search), queriedFrame = q.has('frame') ? Number(q.get('frame')) : null;
  const normalizeFrame = n => Number.isFinite(n) ? Math.max(0, Math.min(maxFrame, Math.trunc(n))) : 0;
  let currentFrame = queriedFrame === null ? 0 : normalizeFrame(queriedFrame), t = currentFrame / fps;
  const $ = s => document.querySelector(s), esc = s => s.replace(/[&<>]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
  const clock = n => `${String(Math.floor(n / 60)).padStart(2,'0')}:${String(Math.floor(n % 60)).padStart(2,'0')}`;
  const clamp = (n, min = 0, max = 1) => Math.max(min, Math.min(max, n));
  const ease = n => { n = clamp(n); return n * n * (3 - 2 * n); };

  function hero(){return `<div class="hero"><div class="hero-copy"><div class="eyebrow">Inspectable delegation policy</div><h1 class="title">Make the<br><span class="accent">choice visible.</span></h1><p class="lede">Explicit model, effort, and context requests—with results verified at the root.</p><div class="hero-words"><b>EXPLICIT CHOICES</b><b>BOUNDED TASKS</b><b>ROOT VERIFICATION</b></div></div><div class="hero-art"><img src="../assets/brand/mars-cost-router-hero.svg" alt="Three deliberate routes meeting at a verified root"></div></div>`}
  function identity(){return `<div class="identity-grid"><div class="identity-copy"><div class="eyebrow">Mars Cost Router</div><h1>INDEPENDENT PROJECT<br>INSTRUCTION-DRIVEN<br><span>INSPECTABLE</span><br>UNOFFICIAL</h1><p>Mars is the project name. <b>Terra</b> and <b>Sol</b> label the requested model lanes.</p></div><div class="identity-rail"><span>PROJECT IDENTITY</span><span>REQUESTED LANES</span><span>ROOT-OWNED VERIFICATION</span></div></div>`}
  function lanes(){const active=t<32.34?'economy':t<37.67?'balanced':'premium';return `<div class="lanes"><div class="eyebrow">Requested model lanes / labels stay visible</div><div class="lane economy ${active==='economy'?'active':''}"><strong>Economy</strong><span>bounded inspection</span><small>TERRA · LOW</small><small>REQUESTED</small></div><div class="lane balanced ${active==='balanced'?'active':''}"><strong>Balanced</strong><span>focused implementation · review</span><small>TERRA · MEDIUM</small><small>REQUESTED</small></div><div class="lane premium ${active==='premium'?'active':''}"><strong>Premium</strong><span>security · uncertainty · difficult debugging</span><small>SOL · HIGH</small><small>REQUESTED</small></div></div>`}
  function terminal(){const commands=['codex plugin marketplace add userbox020/mars-cost-router','codex plugin add mars-cost-router@mars-plugins'];const typed=commands.join('\n').slice(0,Math.max(0,Math.min(commands.join('\n').length,Math.floor((t-43)*8))));return `<div class="install-stack"><div class="terminal"><div class="terminal-top"><span class="dots"><i></i><i></i><i></i></span> SANITIZED INSTALLATION / PUBLIC COMMANDS</div><pre><span class="prompt">$ </span>${esc(typed).replace('\n','\n<span class="prompt">$ </span>')}<span class="cursor"></span></pre><div class="terminal-note">THEN: START A NEW CODEX SESSION · OPEN PLUGIN BROWSER OR @ SURFACE</div></div><div class="install-status"><b>REMOTE INSTALL VERIFIED</b><span>CODEX CLI 0.144.5</span><span>HOSTED CI PASSING</span><span>WINDOWS / LINUX / PYTHON 3.10 / 3.13</span></div></div>`}
  function architecture(){return `<div class="architecture"><div class="architecture-copy"><div class="eyebrow">Instruction-only by design</div><h1>INSPECTABLE<br><span>ARCHITECTURE</span></h1><p>The policy keeps requested settings readable and root verification central.</p><div class="check">Explicit requests · bounded context<br>Scope · integration · verification at the root</div></div><div class="architecture-map"><div class="arch-node"><b>SKILL</b><span>one inspectable entry</span></div><i></i><div class="arch-node"><b>POLICY</b><span>versioned lane guidance</span></div><i></i><div class="arch-node"><b>METADATA</b><span>package context</span></div><div class="root-node">ROOT<br><small>owns verification</small></div></div></div>`}
  function payload(){return `<div class="payload-wrap"><div><div class="eyebrow">Sanitized request example</div><div class="payload">{
  <span class="key">"task_name"</span>: <span class="value">"focused_check"</span>,
  <span class="key">"message"</span>: <span class="value">"Handle one bounded check directly and return findings only. Do not delegate or spawn another agent."</span>,
  <span class="key">"model"</span>: <span class="value">"gpt-5.6-terra"</span>,
  <span class="key">"reasoning_effort"</span>: <span class="value">"medium"</span>,
  <span class="key">"fork_turns"</span>: <span class="value">"none"</span>
}</div></div><div class="intent-card"><div class="eyebrow">Explicit route intent</div><h2>REQUESTED<br><span>SETTINGS</span></h2><p>Model · reasoning effort · bounded context · no inherited turns.</p><div class="intent-pills"><b>MODEL</b><b>EFFORT</b><b>FORK TURNS</b></div><small>Route intent stays visible for review.</small></div></div>`}
  function evidence(){return `<div class="evidence evidence-one"><img src="../assets/evidence/fixed-v1.2-performance.svg" alt="Fixed v1.2 descriptive comparison"><div class="record"><span class="descriptive">PUBLISHED PROVENANCE</span><h2>12 / 12<br><span>IN BOTH ARMS</span></h2><div class="stat"><b>3 PRECOMMITTED PAIRS × 4 TASKS</b>fixed read-only record</div><div class="stat"><b>0 / 0</b>observed automatic retries · reroutes</div><div class="stat"><b>PUBLIC SUMMARY</b>sanitized provenance published</div></div></div>`}
  function record(){return `<div class="evidence-two"><div class="token-panel"><div class="eyebrow">Recorded child tokens</div><h2>NEARLY<br><span>FLAT</span></h2><div class="token-compare"><div><b>356,116</b><small>SELECTIVE</small></div><em>−378<br><small>−0.11% RECORDED</small></em><div><b>356,494</b><small>BASELINE</small></div></div><p>Recorded child-token difference. See Evidence for scope and methodology.</p></div><div class="rate-panel"><img src="../assets/evidence/rate-index.svg" alt="Listed Standard API rate index: Terra 50 and Sol 100"><div class="rate-date">DATED LISTED-RATE INDEX · 2026-07-17</div></div></div>`}
  function method(){return `<div class="method-card"><div class="eyebrow">Public evidence</div><h1>SEPARATE<br>PUBLIC <span>RECORDS</span></h1><div class="method-grid"><div><b>FIXED-SERIES OBSERVATIONS</b><code>FROZEN-SUITE · 96b064…d7bff</code></div><div><b>DATED LISTED-RATE INDEX</b><code>2026-07-17 · TERRA 50 / SOL 100</code></div><div><b>PROVENANCE SUMMARY</b><code>SOURCE · 05e010…c2361</code></div></div><p>Transparent provenance keeps the fixed-series record and dated rate comparison separate.</p><footer>See Evidence for scope and methodology.</footer></div>`}
  function outro(){return `<div class="outro"><div><div class="eyebrow">Mars Cost Router</div><h1>CHOOSE THE LANE.<br>BOUND THE TASK.<br><span class="accent">VERIFY AT THE ROOT.</span></h1><div class="links"><span>INSTALL</span><span>INSPECT</span><span>EVIDENCE</span></div></div><img src="../assets/brand/mars-cost-router-hero.svg" alt="Mars Cost Router routes meeting at root"></div>`}
  function view(){if(t<12)return hero();if(t<27)return identity();if(t<43)return lanes();if(t<58)return terminal();if(t<78)return architecture();if(t<94)return payload();if(t<110)return evidence();if(t<126)return record();if(t<133)return method();return outro()}

  const style=(selector, opacity, y=0, x=0, scale=1)=>{const el=$(selector);if(el){el.style.opacity=opacity.toFixed(3);el.style.transform=`translate(${x.toFixed(2)}px,${y.toFixed(2)}px) scale(${scale.toFixed(4)})`}};
  const captionMotion=(opacity,y=0)=>{const el=$('#caption');if(el){el.style.opacity=opacity.toFixed(3);el.style.transform=`translate(-50%,${y.toFixed(2)}px)`}};
  function applyMotion(c){const local=t-c[0],span=c[1]-c[0],enter=ease(local/.5),exit=c[1]===duration?1:ease((span-local)/.28),presence=Math.min(enter,exit),scene=cue.indexOf(c),drift=Math.sin(t*.42),slow=Math.sin(t*.17);$('#scene').style.opacity=presence.toFixed(3);$('#scene').style.transform=`translateY(${((1-enter)*18-(1-exit)*8).toFixed(2)}px)`;$('#planet').style.transform=`translate(${(slow*22+t*.32).toFixed(2)}px,${(drift*12-t*.12).toFixed(2)}px) scale(${(1+Math.sin(t*.11)*.012).toFixed(4)})`;$('#stars').style.transform=`translate(${(-t*.12).toFixed(2)}px,${(Math.sin(t*.18)*5).toFixed(2)}px)`;captionMotion(presence,(1-enter)*10);
    if(scene===0){style('.hero-copy',ease((local-.08)/.7),18*(1-ease((local-.08)/.7)));style('.hero-art',ease((local-.28)/.8),-18*(1-ease((local-.28)/.8)),10*Math.sin(t*.4),.985+.015*ease((local-.28)/.8));}
    if(scene===1){style('.identity-copy',ease((local-.1)/.65),22*(1-ease((local-.1)/.65)));style('.identity-rail',ease((local-.35)/.65),0,18*(1-ease((local-.35)/.65)));}
    if(scene===2)document.querySelectorAll('.lane').forEach((el,i)=>{const a=ease((local-.15-i*.25)/.45);el.style.opacity=a.toFixed(3);el.style.transform=`translateX(${(1-a)*-28+(el.classList.contains('active')?18:0)}px)`});
    if(scene===3){const a=ease((local-.12)/.5);style('.install-stack',a,22*(1-a));const cursor=$('.cursor');if(cursor)cursor.style.opacity=(Math.floor(t*2)%2?'.2':'1');}
    if(scene===4){style('.architecture-copy',ease((local-.1)/.65),22*(1-ease((local-.1)/.65)));style('.architecture-map',ease((local-.34)/.75),-12*(1-ease((local-.34)/.75)),14*(1-ease((local-.34)/.75)),.98+.02*ease((local-.34)/.75));}
    if(scene===5){style('.payload-wrap>div:first-child',ease((local-.1)/.6),18*(1-ease((local-.1)/.6)));style('.intent-card',ease((local-.35)/.65),18*(1-ease((local-.35)/.65)));}
    if(scene===6){style('.evidence-one img',ease((local-.1)/.65),18*(1-ease((local-.1)/.65)),-10*(1-ease((local-.1)/.65)),.98+.02*ease((local-.1)/.65));style('.evidence-one .record',ease((local-.3)/.65),18*(1-ease((local-.3)/.65)));}
    if(scene===7){style('.token-panel',ease((local-.1)/.65),18*(1-ease((local-.1)/.65)));style('.rate-panel',ease((local-.3)/.65),18*(1-ease((local-.3)/.65)));}
    if(scene===8)style('.method-card',ease((local-.08)/.65),22*(1-ease((local-.08)/.65)),0,.985+.015*ease((local-.08)/.65));
    if(scene===9){style('.outro>div',ease((local-.1)/.7),20*(1-ease((local-.1)/.7)));style('.outro img',ease((local-.32)/.8),-14*(1-ease((local-.32)/.8)),10*Math.sin(t*.3),.985+.015*ease((local-.32)/.8));}}
  function render(){const c=cue.find(x=>t>=x[0]&&t<x[1])||cue.at(-1), index=cue.indexOf(c);$('#scene').innerHTML=view();$('#caption').textContent=c[2];$('#clock').textContent=clock(t);$('#frame-number').textContent=`${String(currentFrame).padStart(4,'0')} / 4200`;$('#chapter').textContent=`${String(index+1).padStart(2,'0')} / ${chapters[index]}`;if(q.get('clean')==='1')$('#guides').style.display='none';applyMotion(c)}
  window.setFrame=n=>{currentFrame=normalizeFrame(Number(n));t=currentFrame/fps;render();return {frame:currentFrame,time:t}};
  render();if(queriedFrame===null){const start=performance.now();const tick=now=>{t=Math.min(duration-1/fps,(now-start)/1000);currentFrame=Math.min(maxFrame,Math.floor(t*fps));render();requestAnimationFrame(tick)};requestAnimationFrame(tick)}
})();
